const LAUNCH_COMBOS = [
  {
    id: 'combo-1',
    name: 'The Ultimate Snack Combo',
    slug: 'ultimate-snack-combo',
    price: 999,
    originalPrice: 1299,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/ultimate_snakc_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/ultimate_snakc_combo.jpg'],
    badge: 'ALL 6 @ ₹999',
    description: 'The mega celebration pack: Air Fried Beetroot, Broccoli & Ragi Chips + Classic Jowar Nutty, Premium Ragi Elaichi & Millet Honey Oats Cookies.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-2',
    name: '3 Pack Combo',
    slug: '3-pack-makhana-combo',
    price: 569,
    originalPrice: 749,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/3_pack_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/3_pack_combo.jpg'],
    badge: 'ONLY ₹569',
    description: 'Pure roasted fox nuts trio: Cream & Onion, Himalayan Pink Salt & Fiery Peri Peri Makhana.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-3',
    name: '2 Cookies Combo',
    slug: '2-cookies-combo',
    price: 369,
    originalPrice: 499,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/2_cokkie_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/2_cokkie_combo.jpg'],
    badge: 'ONLY ₹369',
    description: 'Millet cookie duo: Classic Jowar Nutty Cookies & Premium Ragi Elaichi Cookies. Zero refined sugar.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-4',
    name: 'Classic Combo',
    slug: 'classic-combo',
    price: 369,
    originalPrice: 499,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/classical_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552422/classical_combo.jpg'],
    badge: 'ONLY ₹369',
    description: 'Timeless favorites duo: Classic Jowar Nutty Cookies & Millet Honey Oats Cookies.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-5',
    name: 'Ragi + Broccoli Combo',
    slug: 'ragi-broccoli-combo',
    price: 349,
    originalPrice: 429,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/WhatsApp_Image_2026-10-06_at_7.57.15_PM.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/WhatsApp_Image_2026-10-06_at_7.57.15_PM.jpg'],
    badge: 'ONLY ₹349',
    description: 'Crunchy guilt-free air fried chips: Air Fried Ragi Chips & Air Fried Broccoli Chips.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-6',
    name: '2 Chips Combo',
    slug: '2-chips-combo',
    price: 349,
    originalPrice: 429,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/WhatsApp_Image_2026-10-06_at_7.57.14_PM.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/WhatsApp_Image_2026-10-06_at_7.57.14_PM.jpg'],
    badge: 'ONLY ₹349',
    description: 'Vibrant & healthy chips duo: Air Fried Beetroot Chips & Air Fried Broccoli Chips.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-7',
    name: '3 Cookies Combo',
    slug: '3-cookies-combo',
    price: 549,
    originalPrice: 749,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/3_cookie_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/3_cookie_combo.jpg'],
    badge: 'ONLY ₹549',
    description: 'Complete millet cookie trio: Classic Jowar Nutty, Premium Ragi Elaichi & Millet Honey Oats Cookies.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: 'combo-8',
    name: '3 Chips Combo',
    slug: '3-chips-combo',
    price: 499,
    originalPrice: 649,
    thumbnail: 'https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/3_chips_combo.jpg',
    images: ['https://res.cloudinary.com/dyf00ptkk/image/upload/v1791552421/3_chips_combo.jpg'],
    badge: 'ONLY ₹499',
    description: 'The ultimate guilt-free chips trio: Air Fried Beetroot Chips, Air Fried Ragi Chips & Air Fried Broccoli Chips.',
    category: 'Launch Offers',
    stock: 100,
    weight: 'Combo Pack',
    isFeatured: false,
    isBestSeller: false
  }
];

module.exports = { LAUNCH_COMBOS };
