import json
import re

products = [
    # --- Flavoured Makhanas ---
    {
        "name": "Himalayan Salt Makhana (35g)",
        "slug": "himalayan-salt-makhana-35g",
        "description": "Light, airy fox nuts air-popped and seasoned with pure Himalayan pink salt. High in protein, low in fat, and completely guilt-free. Perfect for evening snacking.",
        "shortDescription": "Air-popped fox nuts with Himalayan pink salt.",
        "price": 99,
        "originalPrice": 129,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/himalayan-salt-makhana.jpeg",
        "images": ["/images/products/himalayan-salt-makhana.jpeg"],
        "stock": 150,
        "weight": "35g",
        "ingredients": ["Fox Nuts (Makhana)", "Himalayan Pink Salt", "Cold Pressed Coconut Oil"],
        "nutritionFacts": { "calories": 121, "protein": 3.4, "carbs": 27, "fat": 0.035, "fiber": 0.175 },
        "tags": ["makhana", "healthy", "low-fat", "himalayan-salt", "35g"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.8,
        "numReviews": 124
    },
    {
        "name": "Himalayan Salt Makhana (75g)",
        "slug": "himalayan-salt-makhana-75g",
        "description": "Light, airy fox nuts air-popped and seasoned with pure Himalayan pink salt.",
        "shortDescription": "Air-popped fox nuts with Himalayan pink salt.",
        "price": 199,
        "originalPrice": 249,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/himalayan-salt-makhana.jpeg",
        "images": ["/images/products/himalayan-salt-makhana.jpeg"],
        "stock": 150,
        "weight": "75g",
        "ingredients": ["Fox Nuts (Makhana)", "Himalayan Pink Salt", "Cold Pressed Coconut Oil"],
        "nutritionFacts": { "calories": 260, "protein": 7.3, "carbs": 57.6, "fat": 0.075, "fiber": 0.375 },
        "tags": ["makhana", "healthy", "low-fat", "himalayan-salt", "75g"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.8,
        "numReviews": 124
    },
    {
        "name": "Himalayan Salt Makhana (100g)",
        "slug": "himalayan-salt-makhana-100g",
        "description": "Light, airy fox nuts air-popped and seasoned with pure Himalayan pink salt.",
        "shortDescription": "Air-popped fox nuts with Himalayan pink salt.",
        "price": 249,
        "originalPrice": 299,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/himalayan-salt-makhana.jpeg",
        "images": ["/images/products/himalayan-salt-makhana.jpeg"],
        "stock": 150,
        "weight": "100g",
        "ingredients": ["Fox Nuts (Makhana)", "Himalayan Pink Salt", "Cold Pressed Coconut Oil"],
        "nutritionFacts": { "calories": 347, "protein": 9.7, "carbs": 76.9, "fat": 0.1, "fiber": 0.5 },
        "tags": ["makhana", "healthy", "low-fat", "himalayan-salt", "100g"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.8,
        "numReviews": 124
    },
    {
        "name": "Black Pepper & Himalayan Salt Makhana (35g)",
        "slug": "black-pepper-makhana-35g",
        "description": "Boldly seasoned with black pepper and Himalayan pink salt. Air-popped, never fried.",
        "shortDescription": "Spicy black pepper flavoured fox nuts.",
        "price": 99,
        "originalPrice": 129,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/black-pepper-makhana.jpeg",
        "images": ["/images/products/black-pepper-makhana.jpeg"],
        "stock": 120,
        "weight": "35g",
        "ingredients": ["Fox Nuts (Makhana)", "Black Pepper Seasoning", "Sunflower Oil", "Salt"],
        "nutritionFacts": { "calories": 124, "protein": 3.3, "carbs": 26, "fat": 0.7, "fiber": 0.175 },
        "tags": ["makhana", "spicy", "black-pepper", "35g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 89
    },
    {
        "name": "Black Pepper & Himalayan Salt Makhana (75g)",
        "slug": "black-pepper-makhana-75g",
        "description": "Boldly seasoned with black pepper and Himalayan pink salt. Air-popped, never fried.",
        "shortDescription": "Spicy black pepper flavoured fox nuts.",
        "price": 199,
        "originalPrice": 249,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/black-pepper-makhana.jpeg",
        "images": ["/images/products/black-pepper-makhana.jpeg"],
        "stock": 120,
        "weight": "75g",
        "ingredients": ["Fox Nuts (Makhana)", "Black Pepper Seasoning", "Sunflower Oil", "Salt"],
        "nutritionFacts": { "calories": 266, "protein": 7.1, "carbs": 55.5, "fat": 1.6, "fiber": 0.375 },
        "tags": ["makhana", "spicy", "black-pepper", "75g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 89
    },
    {
        "name": "Black Pepper & Himalayan Salt Makhana (100g)",
        "slug": "black-pepper-makhana-100g",
        "description": "Boldly seasoned with black pepper and Himalayan pink salt. Air-popped, never fried.",
        "shortDescription": "Spicy black pepper flavoured fox nuts.",
        "price": 249,
        "originalPrice": 299,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/black-pepper-makhana.jpeg",
        "images": ["/images/products/black-pepper-makhana.jpeg"],
        "stock": 120,
        "weight": "100g",
        "ingredients": ["Fox Nuts (Makhana)", "Black Pepper Seasoning", "Sunflower Oil", "Salt"],
        "nutritionFacts": { "calories": 355, "protein": 9.5, "carbs": 74.2, "fat": 2.1, "fiber": 0.5 },
        "tags": ["makhana", "spicy", "black-pepper", "100g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 89
    },
    {
        "name": "Pudina Makhana (35g)",
        "slug": "pudina-makhana-35g",
        "description": "Refreshing mint flavored makhana with aromatic pudina seasoning. Light, cooling, and perfect as an afternoon snack.",
        "shortDescription": "Refreshing mint flavored fox nuts.",
        "price": 99,
        "originalPrice": 129,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/pudina-makhana.jpeg",
        "images": ["/images/products/pudina-makhana.jpeg"],
        "stock": 100,
        "weight": "35g",
        "ingredients": ["Fox Nuts (Makhana)", "Pudina (Mint) Seasoning", "Salt", "Cold Pressed Oil"],
        "nutritionFacts": { "calories": 124, "protein": 3.4, "carbs": 27, "fat": 0.05, "fiber": 0.175 },
        "tags": ["makhana", "pudina", "mint", "35g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.5,
        "numReviews": 65
    },
    {
        "name": "Pudina Makhana (75g)",
        "slug": "pudina-makhana-75g",
        "description": "Refreshing mint flavored makhana with aromatic pudina seasoning. Light, cooling, and perfect as an afternoon snack.",
        "shortDescription": "Refreshing mint flavored fox nuts.",
        "price": 199,
        "originalPrice": 249,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/pudina-makhana.jpeg",
        "images": ["/images/products/pudina-makhana.jpeg"],
        "stock": 100,
        "weight": "75g",
        "ingredients": ["Fox Nuts (Makhana)", "Pudina (Mint) Seasoning", "Salt", "Cold Pressed Oil"],
        "nutritionFacts": { "calories": 266, "protein": 7.3, "carbs": 57.6, "fat": 0.1, "fiber": 0.375 },
        "tags": ["makhana", "pudina", "mint", "75g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.5,
        "numReviews": 65
    },
    {
        "name": "Pudina Makhana (100g)",
        "slug": "pudina-makhana-100g",
        "description": "Refreshing mint flavored makhana with aromatic pudina seasoning. Light, cooling, and perfect as an afternoon snack.",
        "shortDescription": "Refreshing mint flavored fox nuts.",
        "price": 249,
        "originalPrice": 299,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/pudina-makhana.jpeg",
        "images": ["/images/products/pudina-makhana.jpeg"],
        "stock": 100,
        "weight": "100g",
        "ingredients": ["Fox Nuts (Makhana)", "Pudina (Mint) Seasoning", "Salt", "Cold Pressed Oil"],
        "nutritionFacts": { "calories": 347, "protein": 9.7, "carbs": 76.9, "fat": 0.13, "fiber": 0.5 },
        "tags": ["makhana", "pudina", "mint", "100g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.5,
        "numReviews": 65
    },
    {
        "name": "Peri Peri Makhana (35g)",
        "slug": "peri-peri-makhana-35g",
        "description": "Spicy and tangy peri peri flavoured makhana. Boldly seasoned with African spices for those who love a kick. Air-popped, never fried.",
        "shortDescription": "Spicy peri peri flavoured fox nuts.",
        "price": 99,
        "originalPrice": 129,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/peri-peri-makhana.jpeg",
        "images": ["/images/products/peri-peri-makhana.jpeg"],
        "stock": 110,
        "weight": "35g",
        "ingredients": ["Fox Nuts (Makhana)", "Peri Peri Seasoning", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 124, "protein": 3.5, "carbs": 27, "fat": 0.1, "fiber": 0.175 },
        "tags": ["makhana", "peri-peri", "savory", "35g"],
        "isFeatured": False,
        "isBestSeller": True,
        "ratings": 4.7,
        "numReviews": 92
    },
    {
        "name": "Peri Peri Makhana (75g)",
        "slug": "peri-peri-makhana-75g",
        "description": "Spicy and tangy peri peri flavoured makhana. Boldly seasoned with African spices for those who love a kick.",
        "shortDescription": "Spicy peri peri flavoured fox nuts.",
        "price": 199,
        "originalPrice": 249,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/peri-peri-makhana.jpeg",
        "images": ["/images/products/peri-peri-makhana.jpeg"],
        "stock": 110,
        "weight": "75g",
        "ingredients": ["Fox Nuts (Makhana)", "Peri Peri Seasoning", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 266, "protein": 7.5, "carbs": 57.6, "fat": 0.21, "fiber": 0.375 },
        "tags": ["makhana", "peri-peri", "savory", "75g"],
        "isFeatured": False,
        "isBestSeller": True,
        "ratings": 4.7,
        "numReviews": 92
    },
    {
        "name": "Peri Peri Makhana (100g)",
        "slug": "peri-peri-makhana-100g",
        "description": "Spicy and tangy peri peri flavoured makhana. Boldly seasoned with African spices for those who love a kick.",
        "shortDescription": "Spicy peri peri flavoured fox nuts.",
        "price": 249,
        "originalPrice": 299,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/peri-peri-makhana.jpeg",
        "images": ["/images/products/peri-peri-makhana.jpeg"],
        "stock": 110,
        "weight": "100g",
        "ingredients": ["Fox Nuts (Makhana)", "Peri Peri Seasoning", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 347, "protein": 10, "carbs": 76.9, "fat": 0.28, "fiber": 0.5 },
        "tags": ["makhana", "peri-peri", "savory", "100g"],
        "isFeatured": False,
        "isBestSeller": True,
        "ratings": 4.7,
        "numReviews": 92
    },
    {
        "name": "Cream & Onion Makhana (35g)",
        "slug": "cream-onion-makhana-35g",
        "description": "Decadent cream and onion flavor meets light, crispy makhana. A sophisticated snack for those who prefer refined taste.",
        "shortDescription": "Rich cream and onion flavored fox nuts.",
        "price": 99,
        "originalPrice": 129,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/cream-onion-makhana.jpeg",
        "images": ["/images/products/cream-onion-makhana.jpeg"],
        "stock": 95,
        "weight": "35g",
        "ingredients": ["Fox Nuts (Makhana)", "Cream and Onion Flavoring", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 124, "protein": 3.4, "carbs": 27, "fat": 0.08, "fiber": 0.175 },
        "tags": ["makhana", "cream-onion", "premium", "35g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 75
    },
    {
        "name": "Cream & Onion Makhana (75g)",
        "slug": "cream-onion-makhana-75g",
        "description": "Decadent cream and onion flavor meets light, crispy makhana. A sophisticated snack for those who prefer refined taste.",
        "shortDescription": "Rich cream and onion flavored fox nuts.",
        "price": 199,
        "originalPrice": 249,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/cream-onion-makhana.jpeg",
        "images": ["/images/products/cream-onion-makhana.jpeg"],
        "stock": 95,
        "weight": "75g",
        "ingredients": ["Fox Nuts (Makhana)", "Cream and Onion Flavoring", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 266, "protein": 7.3, "carbs": 57.6, "fat": 0.17, "fiber": 0.375 },
        "tags": ["makhana", "cream-onion", "premium", "75g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 75
    },
    {
        "name": "Cream & Onion Makhana (100g)",
        "slug": "cream-onion-makhana-100g",
        "description": "Decadent cream and onion flavor meets light, crispy makhana. A sophisticated snack for those who prefer refined taste.",
        "shortDescription": "Rich cream and onion flavored fox nuts.",
        "price": 249,
        "originalPrice": 299,
        "category": "Flavoured Makhanas",
        "thumbnail": "/images/products/cream-onion-makhana.jpeg",
        "images": ["/images/products/cream-onion-makhana.jpeg"],
        "stock": 95,
        "weight": "100g",
        "ingredients": ["Fox Nuts (Makhana)", "Cream and Onion Flavoring", "Salt", "Sunflower Oil"],
        "nutritionFacts": { "calories": 347, "protein": 9.7, "carbs": 76.9, "fat": 0.23, "fiber": 0.5 },
        "tags": ["makhana", "cream-onion", "premium", "100g"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 75
    },

    # --- Air Fried Chips ---
    {
        "name": "Beetroot Chips (100g)",
        "slug": "beetroot-chips-100g",
        "description": "Crispy air-fried beetroot chips with just the right amount of salt. 70% less oil than regular chips. Crispy, crunchy, and completely guilt-free.",
        "shortDescription": "Air fried beetroot chips with minimal oil.",
        "price": 129,
        "originalPrice": 169,
        "category": "Air Fried Chips",
        "thumbnail": "https://res.cloudinary.com/dyf00ptkk/image/upload/v1790267216/WhatsApp_Image_2026-09-21_at_2.51.41_PM.jpg",
        "images": ["https://res.cloudinary.com/dyf00ptkk/image/upload/v1790267216/WhatsApp_Image_2026-09-21_at_2.51.41_PM.jpg"],
        "stock": 145,
        "weight": "100g",
        "ingredients": ["Beetroot", "Salt", "Sunflower Oil (minimal)"],
        "nutritionFacts": { "calories": 130, "protein": 2.1, "carbs": 27.8, "fat": 2.0, "fiber": 2.2 },
        "tags": ["chips", "beetroot", "air-fried", "healthy", "low-fat"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.7,
        "numReviews": 112
    },
    {
        "name": "Broccoli Chips (100g)",
        "slug": "broccoli-chips-100g",
        "description": "Flavorful broccoli air-fried chips. 70% less oil than regular chips. Crispy, crunchy, and completely guilt-free.",
        "shortDescription": "Broccoli air-fried chips with minimal oil.",
        "price": 129,
        "originalPrice": 169,
        "category": "Air Fried Chips",
        "thumbnail": "/images/products/broccoli-chips.jpeg",
        "images": ["/images/products/broccoli-chips.jpeg"],
        "stock": 135,
        "weight": "100g",
        "ingredients": ["Broccoli", "Spices", "Salt", "Sunflower Oil (minimal)"],
        "nutritionFacts": { "calories": 140, "protein": 2.3, "carbs": 28.5, "fat": 2.2, "fiber": 2.4 },
        "tags": ["chips", "broccoli", "air-fried", "healthy", "low-fat"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.8,
        "numReviews": 98
    },
    {
        "name": "Ragi Chips (100g)",
        "slug": "ragi-chips-100g",
        "description": "Perfectly salted and crispy air-fried ragi chips. 70% less oil than regular chips. Crispy, crunchy, and completely guilt-free.",
        "shortDescription": "Salted air-fried ragi chips with minimal oil.",
        "price": 129,
        "originalPrice": 169,
        "category": "Air Fried Chips",
        "thumbnail": "https://res.cloudinary.com/dyf00ptkk/image/upload/v1790267215/WhatsApp_Image_2026-09-21_at_2.51.41_PM_1.jpg",
        "images": ["https://res.cloudinary.com/dyf00ptkk/image/upload/v1790267215/WhatsApp_Image_2026-09-21_at_2.51.41_PM_1.jpg"],
        "stock": 125,
        "weight": "100g",
        "ingredients": ["Ragi", "Sea Salt", "Sunflower Oil (minimal)"],
        "nutritionFacts": { "calories": 130, "protein": 2.1, "carbs": 27.8, "fat": 2.0, "fiber": 2.2 },
        "tags": ["chips", "ragi", "air-fried", "healthy", "low-fat"],
        "isFeatured": False,
        "isBestSeller": False,
        "ratings": 4.6,
        "numReviews": 87
    },

    # --- No Sugar No Palm Oil Millet Cookies ---
    {
        "name": "Honey & Oats Cookies (100g)",
        "slug": "honey-oats-cookies-100g",
        "description": "Delicious and nutritious honey and oats cookies with absolutely no added sugar or palm oil.",
        "shortDescription": "Nutritious honey oats cookies, zero sugar, no palm oil.",
        "price": 149,
        "originalPrice": 199,
        "category": "No Sugar No Palm Oil Millet Cookies",
        "thumbnail": "/images/products/honey-oats-cookies.jpeg",
        "images": ["/images/products/honey-oats-cookies.jpeg"],
        "stock": 120,
        "weight": "100g",
        "ingredients": ["Oats", "Honey", "Coconut Oil", "Sea Salt", "Baking Powder"],
        "nutritionFacts": { "calories": 410, "protein": 8.2, "carbs": 62.3, "fat": 14.5, "fiber": 3.1 },
        "tags": ["cookies", "oats", "honey", "no-sugar", "no-palm-oil", "healthy"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.9,
        "numReviews": 134
    },
    {
        "name": "Jowar & Nuts Cookies (100g)",
        "slug": "jowar-nuts-cookies-100g",
        "description": "Delicious and nutritious jowar and nuts cookies with absolutely no added sugar or palm oil.",
        "shortDescription": "Nutritious jowar and nuts cookies, zero sugar, no palm oil.",
        "price": 149,
        "originalPrice": 199,
        "category": "No Sugar No Palm Oil Millet Cookies",
        "thumbnail": "/images/products/jowar-nuts-cookies.jpeg",
        "images": ["/images/products/jowar-nuts-cookies.jpeg"],
        "stock": 115,
        "weight": "100g",
        "ingredients": ["Jowar Flour", "Nuts", "Natural Sweetener (Stevia)", "Coconut Oil", "Sea Salt", "Baking Powder"],
        "nutritionFacts": { "calories": 410, "protein": 8.2, "carbs": 62.3, "fat": 14.5, "fiber": 3.1 },
        "tags": ["cookies", "jowar", "nuts", "no-sugar", "no-palm-oil", "healthy"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.8,
        "numReviews": 110
    },
    {
        "name": "Ragi & Elaichi Cookies (100g)",
        "slug": "ragi-elaichi-cookies-100g",
        "description": "Delicious and nutritious ragi and elaichi cookies with absolutely no added sugar or palm oil.",
        "shortDescription": "Nutritious ragi and elaichi cookies, zero sugar, no palm oil.",
        "price": 149,
        "originalPrice": 199,
        "category": "No Sugar No Palm Oil Millet Cookies",
        "thumbnail": "/images/products/ragi-elaichi-cookies.jpeg",
        "images": ["/images/products/ragi-elaichi-cookies.jpeg"],
        "stock": 125,
        "weight": "100g",
        "ingredients": ["Ragi Flour", "Elaichi", "Natural Sweetener (Stevia)", "Coconut Oil", "Sea Salt", "Baking Powder"],
        "nutritionFacts": { "calories": 410, "protein": 8.2, "carbs": 62.3, "fat": 14.5, "fiber": 3.1 },
        "tags": ["cookies", "ragi", "elaichi", "no-sugar", "no-palm-oil", "healthy"],
        "isFeatured": True,
        "isBestSeller": True,
        "ratings": 4.7,
        "numReviews": 98
    }
]

with open("backend/seed.js", "r", encoding="utf-8") as f:
    content = f.read()

js_products = json.dumps(products, indent=4)
content = re.sub(r'const products = \[.*?\];', f'const products = {js_products};', content, flags=re.DOTALL)

with open("backend/seed.js", "w", encoding="utf-8") as f:
    f.write(content)

print("Updated backend/seed.js")
